services:
  kv1:
    environment:
      - NODES_FILE=/cluster/nodes.json
      - NODES_REFRESH_INTERVAL=3
    volumes:
      - ./nodes.json:/cluster/nodes.json:ro

  kv2:
    environment:
      - NODES_FILE=/cluster/nodes.json
      - NODES_REFRESH_INTERVAL=3
    volumes:
      - ./nodes.json:/cluster/nodes.json:ro

  kv3:
    environment:
      - NODES_FILE=/cluster/nodes.json
      - NODES_REFRESH_INTERVAL=3
    volumes:
      - ./nodes.json:/cluster/nodes.json:ro
